# This is a basic workflow to help you get started with Actions

name: "Send Weekly Metrics Email"

# Controls when the workflow will run
on:
  # runs on mondays at 9:30am UTC
  schedule:
    - cron: 30 9 * * 1 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send_mail:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: check out repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          token: ${{ secrets.READ_GITHUB_ACTIONS_PAT }}

       # Runs a single command using the runners shell
      - name: install python sendgrid
        run: |
          sudo pip3 install sendgrid 

      # Runs a single command using the runners shell
      - name: Run python script
        env:
          SENDGRID_SANDBOX_API_KEY: ${{ secrets.SENDGRID_SANDBOX_API_KEY }}
        run: python3 ./python/sendmail.py -t weekly_list.txt -f noreply@rockwellautomation.com -c ./report/metrics.html --subject='DevSecOps Metrics - Weekly Report'
